---
- name: PostgreSQL master checker
  shell: sudo -iu postgres psql -c "{{ item }}"
  loop:
    - "SELECT application_name, state, sync_priority, sync_state FROM pg_stat_replication;"
    - "SELECT * FROM pg_stat_replication;"
    - "SELECT datname AS database_name FROM pg_database;"
    - "SELECT schema_name FROM information_schema.schemata;"
    - "SELECT schemaname, tablename FROM pg_catalog.pg_tables;"
  register: check

- name: Store check to file
  local_action:
    module: copy
    content: "-- {{ item['item'] }}\n{{ item['stdout'] }}"
    dest: "../../files/master_check-{{ item['item'] | replace(',', '_') | replace(';', '-') | replace(' ', '-') }}.txt"
  loop: "{{ check['results'] }}"

- name: PostgreSQL master activity
  shell: sudo -iu postgres psql -c "{{ item }}"
  loop:
    - "DROP SCHEMA IF EXISTS test_schema CASCADE; CREATE SCHEMA test_schema;"
    - "CREATE TABLE test_schema.test_table(id serial primary key, value varchar(50));"
    - "INSERT INTO test_schema.test_table(value) VALUES ('first'),('second');"
  register: activity

- name: Store activity to file
  local_action:
    module: copy
    content: "-- {{ item['item'] }}\n{{ item['stdout'] }}"
    dest: "../../files/master_activity-{{ item['item'] | replace(',', '_') | replace(';', '-') | replace(' ', '-') | replace(\"'\", '') }}.txt"
  loop: "{{ activity['results'] }}"
