---
- name: Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present
  tags:
    - install-epel-repo
    - deploy

- name: Install PostgreSQL repo
  yum:
    name: http://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  tags:
    - install-postgresql-repo
    - install-postgresql
    - deploy

- name: Uninstall PostgreSQL
  yum:
    name: postgresql11-server
    state: absent
  tags:
    - uninstall-postgresql
    - deploy

- name: Remove PostgreSQL data dir
  file:
    path: "/var/lib/pgsql/11/data"
    state: absent
  tags:
    - remove-postgresql-data-dir
    - init-postgresql
    - deploy

- name: Install PostgreSQL
  yum:
    name: postgresql11-server
  tags:
    - install-postgresql
    - deploy

- name: Init PostgreSQL
  shell: /usr/pgsql-11/bin/postgresql-11-setup initdb
  args:
    creates: /var/lib/pgsql/11/data/postgresql.conf
  tags:
    - init-postgresql
    - deploy

- name: Force clear PostgreSQL data dir
  file:
    path: "/var/lib/pgsql/11/data"
    state: absent
  tags:
    - force-clear-postgresql-data-dir
    - deploy

- name: Create PostgreSQL data
  file:
    path: "/var/lib/pgsql/11/data"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  tags:
    - create-postgresql-data-dir
    - copy-master-data
    - deploy

- name: Update all packages
  yum:
    name: '*'
    state: latest
  tags:
    - packages-update

#- name: Install python3-pip for pexpect promt answering
#  yum:
#    name: python3-pip
#    state: latest
#  tags:
#    - install-python3-pip
#    - deploy

- name: Install python-pip for pexpect promt answering
  yum:
    name: python-pip
    state: latest
  tags:
    - install-python-pip
    - deploy

#- name: Install pexpect promt answering
#  yum:
#    name: pexpect
#    state: latest
#  tags:
#    - install-pexpect
#    - deploy

#- name: Pip3 install pexpect
#  pip:
#    name: pexpect==3.3
#    state: present
#    executable: pip3
#  tags:
#    - install-python3-pexpect
#    - deploy

- name: Pip install pexpect
  pip:
    name: pexpect==3.3
    state: present
  tags:
    - install-python-pexpect
    - deploy

- name: Clear PostgreSQL data dir
  file:
    path: "/var/lib/pgsql/11/data"
    state: absent
  tags:
    - clear-postgresql-data-dir
    - copy-master-data
    - init-postgresql
    - deploy

- name: Copy database from master to slave
  become_user: postgres
  expect:
    command: pg_basebackup -X stream -h 192.168.40.10 -D /var/lib/pgsql/11/data/ -P -U replicator -W
    responses:
      '(.*):(.*)': 'replicator'
  notify:
    - restart-postgresql
  register:  copy_master_data_dir_log
  tags:
    - copy-master-data-dir
    - copy-master-data
    - deploy

- name: Copy database from master to slave
  shell: pg_basebackup -X stream -h 192.168.40.10 -D /var/lib/pgsql/11/data/ -P -U replicator
  tags:
    - copy-master-data-trust

- name: Collect pg.conf-files
  copy:
    src: ../files/{{ item }}
    dest: /var/lib/pgsql/11/data/{{ item }}
    owner: postgres
    group: postgres
    force: yes
  loop:
    - recovery.conf
    - postgresql.conf
  tags:
    - collect-pg.conf-files
    - deploy
  notify:
    - restart-postgresql

- name: Print copy_master_data_dir_log
  debug:
    msg: "{{ copy_master_data_dir_log }}"
  tags:
    - copy-master-data-dir
    - copy-master-data
